# load packages
library(shiny)
library(ygdashboard)
library(shinyjs)
library(shinycssloaders)
library(shinyFeedback)
library(shinyWidgets)
library(ggplot2)
library(purrr)
library(googleVis)
library(bsplus)
library(stringr)

# Load the template components
source("header.R")
source("sidebar.R")
source("profile_box.R")
source("about_box.R")
source("skills_box.R")
source("network_box.R")
source("project_box.R")
source("publication_box.R")
source("main_box.R")
source("body.R")
source("dashboardControlbar.R")
