#' Launch the shinyCV web application to view your beautiful CV.
#'
#' @param cv_mode The content to display in the CV. There are currently 5
#' flavors: "full" which will display the 5 tabPanels, namely formation,
#' projects, teaching, publications and talks; "basic" which will display only
#' formation and projetcs; "academic", which will display formation, projects,
#' teaching and talks; "academic_light", which will display formation, projects,
#' and teaching; "research", which will display formations, projects, publications
#' and talks. By default, cv_mode is set to basic.
#' @param data_source If data_source is "manual", it means that datas need to be
#' generated as in the example of feed_shinyCV(). If data_source is the builder_shinyCV()
#' ("from_cvbuilder") then datas are generated by filling the forms in the dedicated interface
#' ( see build_shinyCV()).
#' @param datas If data_source is "manual" and if datas are NULL, an example is generated
#' using generate_datas_shinyCV; if datas are not NULL, datas should be equal to
#' the list of datas returned by the feed_shinyCV function. In other words,
#' datas <- feed_shinyCV(profile, about, skills, languages, network,
#'                      formations, projects, tasks, publications,
#'                      publications_screenshots,
#'                      talks, courses, internships)
#' @export
#' @examples
#' view_shinyCV(cv_mode = "basic", data_source = "manual")

view_shinyCV <- function(cv_mode = "basic", data_source = "manual", datas = NULL) {
  if (is.null(cv_mode)) {
    stop("cv_mode cannot be NULL")
  }
  if (is.null(data_source)) {
    stop("data_source cannot be NULL")
  }

  # recover cv mode from the function argument and set
  # it as an object accessible for the view_shinyCV function
  # set it as global variable
  cv_mode <<- match.arg(
    arg = cv_mode,
    choices = c(
      "basic",
      "full",
      "academic",
      "academic_light",
      "research"
    )
  )

  data_source <<- match.arg(
    arg = data_source,
    choices = c(
      "manual",
      "from_cvbuilder"
    )
  )

  # load datas
  if (data_source == "manual") {
    if (is.null(datas)) {
      generate_datas_shinyCV()
      datas <<- feed_shinyCV(temp_profile, temp_about, temp_skills, temp_languages,
                             temp_network, temp_formations, temp_projects, temp_tasks,
                             temp_publications, publications_screenshots = list(),
                             temp_talks, temp_courses, temp_internships)
    } else {
      datas <<- datas
    }
  } else if (data_source == "from_cvbuilder") {
    # copy the new version of the CV before launching the viewer
    from <- system.file("App/cv_builder/www/data_cv.rds", package = "shinyCV")
    to <- system.file("App/cv_viewer/www/", package = "shinyCV")
    file.copy(from = from, to = to)
    # copy the profile image
    from <- system.file("App/cv_builder/www/Profile_img_saved/0.png", package = "shinyCV")
    to <- system.file("App/cv_viewer/www/Profile_img_saved/", package = "shinyCV")
    file.copy(from = from, to = to)
    # copy the publications screenshots from builder to viewer
    to <- system.file("App/cv_viewer/www/Publications_img_saved/", package = "shinyCV")
    file_list <- list.files(system.file("App/cv_builder/www/Publications_img_saved/", package = "shinyCV"))
    lapply(seq_along(file_list), FUN = function(i) {
      from <- system.file(paste0("App/cv_builder/www/Publications_img_saved/", file_list[i]),
                          package = "shinyCV")
      file.copy(from, to)
    })
  }

  # launch the viewer
  shiny::runApp(appDir = system.file("App", "cv_viewer", package = "shinyCV"),
                display.mode = "normal")
}
